### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by dominik-ilja** [JohnsHarrison/htmltable#1]
```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="style.css">
  <title>Document</title>
</head>

<body>
  <div>
    <table class="plan-table">
      <thead>
        <td colspan="2"></td>
        <th>Free plan</th>
        <th>Lite plan</th>
        <th>Smart plan</th>
        <th>Fleet plan</th>
      </thead>
      <tbody>
        <tr>
          <th colspan="2">Subscription fee</th>
          <td>None</td>
          <td>3.99/mo (+$3 for each extra camera)</td>
          <td>$7.99/mo (+$6 for each extra camera)</td>
          <td>$15.99/mo (+$12 for extra camera up)</td>
        </tr>
        <tr>
          <th colspan="2">Max. Dashcams/Account</th>
          <td>1</td>
          <td>15</td>
          <td>15</td>
          <td>999</td>
        </tr>
        <tr>
          <th colspan="2">Users per Account</th>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>
            Owner: 1<br>
            Admin: 10<br>
            Driver: 1 (per dashcam)
          </td>
        </tr>
        <tr>
          <th colspan="2">Live view / Day</th>
          <td>10 minutes</td>
          <td>30 minutes</td>
          <td>Unlimited</td>
          <td>Unlimited</td>
        </tr>
        <tr>
          <th colspan="2">Cloud Storage</th>
          <td>5GB</td>
          <td>5GB per dashcam</td>
          <td>10GB per dashcam</td>
          <td>15GB per dashcam</td>
        </tr>
        <tr>
          <th colspan="2">Live Event Upload<i>*</i></th>
          <td>2 Days</td>
          <td>7 Days</td>
          <td>30 Days</td>
          <td>30 Days</td>
        </tr>

        <tr>
          <th colspan="2">Push Notifications</td>
          <td>✓</td>
          <td>✓</td>
          <td>✓</td>
          <td>✓</td>
        </tr>
        <tr>
          <th colspan="2">Voice Call</td>
          <td>✓</td>
          <td>✓</td>
          <td>✓</td>
          <td>✓</td>
        </tr>
        <tr>
          <th colspan="2">Cloud Battery **Available with BLACKVUE battery</td>
          <td>✓</td>
          <td>✓</td>
          <td>✓</td>
          <td>✓</td>
        </tr>
        <tr>
          <th colspan="2">Fatigue Risk Alert</td>
          <td>✓</td>
          <td>✓</td>
          <td>✓</td>
          <td>✓</td>
        </tr>
        <tr>
          <th colspan="2">Live GPS</td>
          <td>✓</td>
          <td>✓</td>
          <td>✓</td>
          <td>✓</td>
        </tr>
        <tr>
          <th colspan="2">Driving Reports<i>*</i></td>
          <td>✓</td>
          <td>✓</td>
          <td>✓</td>
          <td>✓</td>
        </tr>
        <tr>
          <th colspan="2">GPS Tracking</td>
          <td>✕</td>
          <td>✕</td>
          <td>90 days</td>
          <td>90 days</td>
        </tr>
        <tr>
          <th colspan="2">Video On Map</td>
          <td>✕</td>
          <td>✕</td>
          <td>✓</td>
          <td>✓</td>
        </tr>
        <tr>
          <th colspan="2">E-mail Notifications</td>
          <td>✕</td>
          <td>✕</td>
          <td>✕</td>
          <td>✓</td>
        </tr>
        <tr>
          <th colspan="2">Multi Live View (Fleeta Web Viewer)</td>
          <td>✕</td>
          <td>✕</td>
          <td>✕</td>
          <td>✓</td>
        </tr>
        <tr>
          <th colspan="2">Geofence Setup (Fleeta Web Viewer) and Alerts</td>
          <td>✕</td>
          <td>✕</td>
          <td>✕</td>
          <td>✓</td>
        </tr>
        <tr>
          <th rowspan="3">Support Software</th>
          <th scope="row">BLACKVUE APP</th>
          <td>✓</td>
          <td>✓</td>
          <td>✓</td>
          <td>✕</td>
        </tr>
        <tr>
          <th scope="row">Fleeta APP <a href="#">What is Fleeta?</a></th>
          <td>✕</td>
          <td>✕</td>
          <td>✕</td>
          <td>✓</td>
        </tr>
        <tr>
          <th scope="row">Fleeta Web Viewer <a href="#">What is Fleeta?</a></th>
          <td>✕</td>
          <td>✕</td>
          <td>✕</td>
          <td>✓</td>
        </tr>
      </tbody>
    </table>
  </div>
</body>

</html>
```

```css
div {
  padding: 1rem;
}

table {
  --border-color: hsl(0, 0%, 80%);

  width: 100%;
  text-align: left;
  background: #fff;
  border-width: 1px 0;
  border-style: solid;
  border-color: var(--border-color);
  border-collapse: collapse;
}

td,
th {
  padding: 0.5rem;
  border-right: 1px solid var(--border-color);
}

td:last-child,
th:last-child {
  border-right: none;
}

tr {
  border-bottom: 1px solid var(--border-color);
}

/* tr:nth-child(even) {
  background-color: #fafafa;
} */

td {
  border-bottom: 1px solid var(--border-color);
}

tbody th {
  font-weight: 400;
}

```
